/**
 * PDF Watermark Module — The Vault Investigates / TruthDrop.io
 *
 * Stamps every exported PDF with four required chain-of-custody elements:
 *   1. Researcher alias/name (from their profile)
 *   2. UTC export timestamp
 *   3. Static text: "For investigative use only — The Vault Investigates / TruthDrop.io"
 *   4. Unique document ID (UUID v4, logged to export_logs table)
 *
 * Watermark layout:
 *   - Diagonal grey overlay on every page (hard to crop out)
 *   - Two-line footer bar on every page:
 *       Line 1: Researcher alias + export timestamp
 *       Line 2: Doc ID in full (monospace, clearly readable)
 *
 * Called only from server-side tRPC procedures — never from the client.
 */

import { PDFDocument, rgb, StandardFonts, degrees } from "pdf-lib";

export interface WatermarkOptions {
  /** Researcher alias or display name */
  researcherAlias: string;
  /** Unique document ID (UUID v4) — generated by caller, logged to DB */
  documentId: string;
  /** UTC export timestamp as ISO string */
  exportedAt: string;
}

/**
 * Apply watermark to a PDF buffer.
 * Returns the watermarked PDF as a Uint8Array.
 */
export async function applyWatermark(
  pdfBytes: Uint8Array | ArrayBuffer,
  opts: WatermarkOptions
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.load(pdfBytes);
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const courier = await pdfDoc.embedFont(StandardFonts.Courier);

  const pages = pdfDoc.getPages();

  // Format timestamp for readability: "2026-04-03 10:28 UTC"
  const tsFormatted = opts.exportedAt.replace("T", " ").replace(/\.\d+Z$/, " UTC").replace("Z", " UTC");

  // Lines for the diagonal watermark (centre of each page)
  const diagonalLines = [
    "FOR INVESTIGATIVE USE ONLY",
    "The Vault Investigates / TruthDrop.io",
    `Researcher: ${opts.researcherAlias}`,
    `Exported:   ${tsFormatted}`,
    // Split UUID into two groups of 18 chars so it fits when rotated
    `Doc ID: ${opts.documentId.substring(0, 18)}`,
    `        ${opts.documentId.substring(18)}`,
  ];

  // Footer line 1: researcher + timestamp
  const footerLine1 = `The Vault Investigates  |  Researcher: ${opts.researcherAlias}  |  ${tsFormatted}`;
  // Footer line 2: full document ID, clearly labelled
  const footerLine2 = `Document ID: ${opts.documentId}`;

  const footerTotalHeight = 34; // two lines + padding

  for (const page of pages) {
    const { width, height } = page.getSize();

    // ── Diagonal watermark overlay ──────────────────────────────────────────
    const lineHeight = 18;
    const totalHeight = diagonalLines.length * lineHeight;
    const startY = height / 2 + totalHeight / 2;

    diagonalLines.forEach((line, i) => {
      const fontSize = i === 0 ? 13 : 10;
      const font = i === 0 ? helveticaBold : (i >= 4 ? courier : helvetica);
      const textWidth = font.widthOfTextAtSize(line, fontSize);

      page.drawText(line, {
        x: width / 2 - textWidth / 2,
        y: startY - i * lineHeight,
        size: fontSize,
        font,
        color: rgb(0.6, 0.6, 0.6),
        opacity: 0.30,
        rotate: degrees(35),
      });
    });

    // ── Footer bar (two lines) ──────────────────────────────────────────────
    // Dark footer background
    page.drawRectangle({
      x: 0,
      y: 0,
      width,
      height: footerTotalHeight,
      color: rgb(0.06, 0.06, 0.06),
      opacity: 0.90,
    });

    // Thin gold separator line at top of footer
    page.drawLine({
      start: { x: 0, y: footerTotalHeight },
      end: { x: width, y: footerTotalHeight },
      thickness: 0.5,
      color: rgb(0.72, 0.59, 0.05),
      opacity: 0.6,
    });

    // Line 1: researcher + timestamp (8pt, grey)
    const line1FontSize = 7.5;
    const line1Width = helvetica.widthOfTextAtSize(footerLine1, line1FontSize);
    page.drawText(footerLine1, {
      x: width / 2 - line1Width / 2,
      y: footerTotalHeight - 13,
      size: line1FontSize,
      font: helvetica,
      color: rgb(0.75, 0.75, 0.75),
      opacity: 1,
    });

    // Line 2: full Doc ID in monospace (8pt, brighter)
    const line2FontSize = 7.5;
    const line2Width = courier.widthOfTextAtSize(footerLine2, line2FontSize);
    page.drawText(footerLine2, {
      x: width / 2 - line2Width / 2,
      y: footerTotalHeight - 25,
      size: line2FontSize,
      font: courier,
      color: rgb(0.88, 0.88, 0.88),
      opacity: 1,
    });
  }

  return pdfDoc.save();
}

/**
 * Create a simple single-page PDF from plain text content.
 * Used when the source data is text (not an existing PDF file).
 */
export async function createTextPdf(
  title: string,
  lines: string[],
  opts: WatermarkOptions
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([595, 842]); // A4
  const { width, height } = page.getSize();
  const margin = 50;
  // Leave 40pt at the bottom for the two-line footer
  let y = height - margin;

  // Title
  page.drawText(title, {
    x: margin,
    y,
    size: 18,
    font: helveticaBold,
    color: rgb(0.05, 0.05, 0.05),
  });
  y -= 30;

  // Divider
  page.drawLine({
    start: { x: margin, y },
    end: { x: width - margin, y },
    thickness: 0.5,
    color: rgb(0.7, 0.7, 0.7),
  });
  y -= 20;

  // Body lines — stop before footer area (40pt from bottom)
  const footerClearance = 50;
  for (const line of lines) {
    if (y < margin + footerClearance) {
      // Add a new page if content overflows
      const newPage = pdfDoc.addPage([595, 842]);
      y = newPage.getSize().height - margin;
    }
    page.drawText(line, {
      x: margin,
      y,
      size: 10,
      font: helvetica,
      color: rgb(0.1, 0.1, 0.1),
      maxWidth: width - margin * 2,
      lineHeight: 14,
    });
    y -= 16;
  }

  const rawBytes = await pdfDoc.save();
  return applyWatermark(rawBytes, opts);
}
